-- DBXNET.AUKO_D definition

CREATE TABLE "DBXNET"."AUKO_D" 
   (	"AUF_NR" CHAR(12), 
	"AU_NR" CHAR(28), 
	"AU_DAT" NUMBER(10,0), 
	"STATUS_KZ" NUMBER(5,0), 
	"FIRM_NR" VARCHAR2(6), 
	"KTO_NR" NUMBER(10,0), 
	"AUF_DAT" NUMBER(10,0), 
	"SPR_SL" NUMBER(5,0), 
	"SAP_CUST_NUMBER" VARCHAR2(100), 
	"SAP_ORDER_NUMBER" VARCHAR2(100), 
	"ORDERID" NUMBER(10,0), 
	"PO_NUMBER" VARCHAR2(30), 
	"IS_MIGRATED" NUMBER(1,0) DEFAULT 0, 
	"FA_KTO_NR" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ORDAT_TABLESPACE" ;

CREATE INDEX "DBXNET"."AUKO_FA_KTO" ON "DBXNET"."AUKO_D" ("FA_KTO_NR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ORDAT_TABLESPACE" ;
  CREATE INDEX "DBXNET"."AUKO_SAP_CUST" ON "DBXNET"."AUKO_D" ("SAP_CUST_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ORDAT_TABLESPACE" ;